#!/bin/bash
# INFOCRAFT 배치 자동 실행 설정 가이드

echo "=========================================="
echo "INFOCRAFT 배치 자동 실행 설정"
echo "=========================================="
echo ""

PROJECT_DIR="/Users/songhyeon-u/IdeaProjects/INFOCRAFT"

echo "두 가지 방법 중 하나를 선택하세요:"
echo ""
echo "1. launchd (macOS 권장)"
echo "2. cron (전통적 방식)"
echo ""
read -p "선택 (1 또는 2): " choice

if [ "$choice" == "1" ]; then
    echo ""
    echo "=========================================="
    echo "launchd 설정 (macOS 권장)"
    echo "=========================================="
    echo ""
    echo "다음 명령어를 실행하세요:"
    echo ""
    echo "# 1. plist 파일 복사"
    echo "cp $PROJECT_DIR/scripts/com.infocraft.batch.plist ~/Library/LaunchAgents/"
    echo ""
    echo "# 2. 등록"
    echo "launchctl load ~/Library/LaunchAgents/com.infocraft.batch.plist"
    echo ""
    echo "# 3. 확인"
    echo "launchctl list | grep infocraft"
    echo ""
    echo "=========================================="
    echo "테스트 실행"
    echo "=========================================="
    echo ""
    echo "launchctl start com.infocraft.batch"
    echo ""
    echo "=========================================="
    echo "제거하려면"
    echo "=========================================="
    echo ""
    echo "launchctl unload ~/Library/LaunchAgents/com.infocraft.batch.plist"
    echo "rm ~/Library/LaunchAgents/com.infocraft.batch.plist"
    echo ""

elif [ "$choice" == "2" ]; then
    echo ""
    echo "=========================================="
    echo "cron 설정"
    echo "=========================================="
    echo ""
    echo "다음 명령어로 crontab 편집:"
    echo ""
    echo "crontab -e"
    echo ""
    echo "아래 줄을 추가 (매일 밤 11시 15분 실행):"
    echo ""
    echo "15 23 * * * /bin/bash $PROJECT_DIR/scripts/run-batch.sh"
    echo ""
    echo "=========================================="
    echo "주의사항"
    echo "=========================================="
    echo ""
    echo "1. macOS에서 cron 사용 시 '시스템 환경설정 > 보안 및 개인정보보호 > 개인정보 보호 > 전체 디스크 접근 권한'에서 cron에 권한 부여 필요"
    echo "2. launchd가 더 권장됨"
    echo ""

else
    echo "잘못된 선택입니다."
    exit 1
fi

echo ""
echo "=========================================="
echo "공통 사항"
echo "=========================================="
echo ""
echo "실행 권한 부여:"
echo "chmod +x $PROJECT_DIR/scripts/run-batch.sh"
echo ""
echo "로그 확인:"
echo "tail -f $PROJECT_DIR/logs/batch-*.log"
echo ""
echo "배치 수동 실행 테스트:"
echo "cd $PROJECT_DIR && ./scripts/run-batch.sh"
echo ""
